services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042" # Exposes Cassandra's CQL port
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
  chat:
    container_name: chat-container
    build: .
    ports:
      - "4000:4000"

volumes:
  cassandra_data: